import type { GetStaticPaths, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import data from "../data.json";
import { Note } from "../types";

interface Props {
  notes: Note[];
}
const Home: NextPage<Props> = ({ notes }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenido a <a href="https://juanmacrossetto.vercel.app/">Los apuntes de juanma!</a>
        </h1>

        <p className={styles.description}>Juanma here! 👋🏻, realizo apuntes a mano sobre las tecnologías más utilizadas.</p>

        <div className={styles.grid}>
          {notes?.map((note) => (
            <a href={`${note.id}`} className={styles.card} key={note.id}>
              <h2>{note.title} &rarr;</h2>
              <p>{note.description}</p>
            </a>
          ))}
        </div>
      </main>
    </div>
  );
};

// export async function getServerSideProps() {
//   const joke = await fetch("https://api.chucknorris.io/jokes/random")
//     .then((res) => res.json())
//     .then((r) => r.value);
//   return {
//     props: { joke },
//   };
// }

export const getStaticProps: GetStaticProps = async () => {
  // const joke = await fetch("https://api.chucknorris.io/jokes/random")
  //   .then((res) => res.json())
  //   .then((r) => r.value);
  return {
    props: { notes: data },
    revalidate: 10,
  };
};

export default Home;
